/**
 * Middleware for error management : either the error is generated by us using customErrors class and we use its parameters, either it's thrown by an external module and we give error 500 by default, returning row error in all cases
 * @param {*} error 
 * @param {*} req 
 * @param {*} res 
 * @param {*} next 
 */
const error = async (error, req, res, next) => {
	res.status(error.statusCode || 500).json({ message: error.message })
}

export default error